### ISSUE TITLE
DDS238-2 Wifi

### ISSUE THREAD

**Issue by thiagoarreguy** [rodgon81/SmartMeter238#2]
It will work with DDS238-2 Wifi ?

**Comment by thiagoarreguy** [comment]
![image](https://user-images.githubusercontent.com/1306452/88607287-38aed180-d055-11ea-95b7-2d07ec92cc01.jpeg)

![image](https://user-images.githubusercontent.com/1306452/88607291-3e0c1c00-d055-11ea-9afe-0fa9c4546f26.jpeg)

**Comment by rodgon81** [comment]
> It will work with DDS238-2 Wifi ?

The odds are low that this library will work.  It only remains to try, the ideal would be to open it and see what it brings.

**Comment by rodgon81** [comment]
...
