### ISSUE TITLE
Home Assistant integration 

### ISSUE THREAD

**Issue by mihaimdinca** [rodgon81/SmartMeter238#3]
Can the DDS-238-4 W be integrated with home assistant after flashing this? If so, what entities are provided. Can you provide detailed instructions regarding flashing for us noobs?

**Comment by rodgon81** [comment]
yes and no....is your meter WISEN or TUYA?
Do you know ESPHome?

**Comment by mihaimdinca** [comment]
It is working with Tuya/ Smart Life
