### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by iosifnicolae2** [rodgon81/SmartMeter238#4]
Do I have to flash this library directly to my DTS238 meter or I flash it to an ESP8266 and then connect the ESP to the meter? If I need to flash it to a separate ESP8266, how do I connect it to the meter? Could you please help us with a wiring diagram?

Thank you!

cc @rodgon81  @Telectroboy

**Comment by rodgon81** [comment]
Hi, is your meter WISEN or TUYA?

**Comment by iosifnicolae2** [comment]
Tuya, DTS238-7 Wifi Ver. TY
https://m.aliexpress.com/item/33024605194.html

Thank you!

**Comment by rodgon81** [comment]
Sorry, for now this library only works with Wisen. If I ever get Tuya Datapoints, I'll try to implement them.
